:description: The Neo4j Java reference for Neo4j version {neo4j-version}.
:keywords: embed Neo4j, build unmanaged extensions, writing extensions, traversal framework, transaction management, JMX, metrics, traversal, framework
[[java-reference]]
= The Neo4j Java Reference v{neo4j-version}

The Java Reference contains information on advanced Java-centric usage of Neo4j.

It covers the following topics:

* xref:extending-neo4j/index.adoc[] -- How to build unmanaged extensions and procedures.
* xref:java-embedded/index.adoc[] -- Instructions on embedding Neo4j in .
* xref:traversal-framework/index.adoc[] -- A walkthrough of the traversal framework.
* xref:transaction-management.adoc[] -- Examples on transaction management in Neo4j.
* xref:jmx-metrics.adoc[] -- How to monitor Neo4j with JMX and a reference of available metrics.

[TIP]
====
You might want to keep the link:{neo4j-javadocs-base-uri}[Neo4j Javadocs (Neo4j Java API Documentation)^] handy while reading.
====

_Who should read this?_

The Java Reference is written for advanced Java developers who want to extend Neo4j's functionality or embed Neo4j in their software.

_Disclaimer_

This guide describes how to make changes to server-sided and deployment functionalities and has no connection with the link:https://neo4j.com/docs/java-manual/current/[Neo4j Java Driver].


ifndef::backend-pdf[]
License: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]

ifdef::backend-pdf[]
License: Creative Commons 4.0
endif::[]