:docs-uri: https://neo4j.com/docs

= docs-java-reference

This repository contains the AsciiDoc and other sources to build the link:{docs-uri}/java-reference/[Neo4j Java Reference].


== Installation

To build these docs locally you need link:https://nodejs.org/en/download/package-manager/[Node & NPM^] installed.

To install the dependencies run:

[source, sh]
----
npm install
----


== Live Preview

To preview the docs, run:

[source, sh]
----
npm run start
----

This builds a set of HTML files in `build/site` and then serves them through an express server at http://localhost:8000.
The start script also listens for changes and automatically rebuilds the files.
You still need to refresh the page to view the changes.


== Contributing

To make changes to this repository, please create a fork of this repo and a new branch to stage your changes.
Your branch should be prefixed with the version number, for example, `5.0-feature-to-document`.

When you are finished with your changes push the branch to your fork and create a Pull Request.
Please add at least one approver.

