:description: How to write, test, and deploy a user-defined aggregation function for Neo4j.

:org-neo4j-procedure-UserAggregationFunction: {neo4j-javadocs-base-uri}/org/neo4j/procedure/UserAggregationFunction.html


[[extending-neo4j-aggregation-functions]]
= User-defined aggregation functions

_User-defined aggregation functions_ are functions that aggregate data and return a single result.
For a comparison between user-defined procedures, functions, and aggregation functions, see xref:extending-neo4j/customized-code.adoc[].


[[call-user-defined-aggregation-function]]
== Call an aggregation function

User-defined aggregation functions are called in the same way as any other Cypher aggregation function.
The function name must be fully qualified, so a function named `longestString` defined in the package `org.neo4j.examples` could be called using:

[source, cypher, role="noplay"]
----
MATCH (p: Person) WHERE p.age = 36
RETURN org.neo4j.examples.longestString(p.name)
----


[[writing-user-defined-aggregation-function]]
== Writing a user-defined aggregation function

User-defined aggregation functions are annotated with `@UserAggregationFunction`.
The annotated function must return an instance of an aggregator class.
An aggregator class contains one method annotated with `@UserAggregationUpdate` and one method annotated with `@UserAggregationResult`.
The method annotated with `@UserAggregationUpdate` will be called multiple times and enables the class to aggregate data.
When the aggregation is done, the method annotated with `@UserAggregationResult` will be called once and the result of the aggregation will be returned.

Particular things to note:

* All functions are annotated with `@UserAggregationFunction`.
* The aggregation function name is required to be namespaced and is not allowed in one of the reserved namespaces.
* If a user defined aggregation function is registered with the same name as a built-in function in a deprecated namespace the built-in function will be shadowed.


See xref:extending-neo4j/values-and-types.adoc[] for details on values and types.

For more details, see the Neo4j Javadocs for link:{org-neo4j-procedure-UserAggregationFunction}[`org.neo4j.procedure.UserAggregationFunction`^].

[NOTE]
====
The correct way to signal an error from within an aggregation function is to throw `RuntimeException`.
====

[source, java]
----
package example;

import org.neo4j.procedure.Description;
import org.neo4j.procedure.Name;
import org.neo4j.procedure.UserAggregationFunction;
import org.neo4j.procedure.UserAggregationResult;
import org.neo4j.procedure.UserAggregationUpdate;

public class LongestString
{
    @UserAggregationFunction
    @Description( "org.neo4j.function.example.longestString(string) - aggregates the longest string found" )
    public LongStringAggregator longestString()
    {
        return new LongStringAggregator();
    }

    public static class LongStringAggregator
    {
        private int longest;
        private String longestString;

        @UserAggregationUpdate
        public void findLongest(
                @Name( "string" ) String string )
        {
            if ( string != null && string.length() > longest)
            {
                longest = string.length();
                longestString = string;
            }
        }

        @UserAggregationResult
        public String result()
        {
            return longestString;
        }
    }
}
----


== Integration tests

Tests for user-defined aggregation functions are created in the same way as those for normal user-defined functions.


.A template for testing a user-defined aggregation function that finds the longest string.
[source, java]
----
package example;

import org.junit.Rule;
import org.junit.Test;
import org.neo4j.driver.v1.*;
import org.neo4j.harness.junit.Neo4jRule;

import static org.hamcrest.core.IsEqual.equalTo;
import static org.junit.Assert.assertThat;

public class LongestStringTest
{
    // This rule starts a Neo4j instance
    @Rule
    public Neo4jRule neo4j = new Neo4jRule()

            // This is the function to test
            .withAggregationFunction( LongestString.class );

    @Test
    public void shouldAllowIndexingAndFindingANode() throws Throwable
    {
        // This is in a try-block, to make sure you close the driver after the test
        try( Driver driver = GraphDatabase.driver( neo4j.boltURI() , Config.build().withEncryptionLevel( Config.EncryptionLevel.NONE ).toConfig() ) )
        {
            // Given
            Session session = driver.session();

            // When
            String result = session.run( "UNWIND ["abc", "abcd", "ab"] AS string RETURN example.longestString(string) AS result").single().get("result").asString();

            // Then
            assertThat( result, equalTo( "abcd" ) );
        }
    }
}
----

[[reserved-and-deprecated-namespaces]]
== Reserved and deprecated function namespaces

[[reserved-and-deprecated-function-namespaces]]
.Overview of reserved and deprecated function namespaces and names
[options="header", cols="m,m"]
|===
| Reserved                      | Deprecated
| date                          |abac.*
| date.realtime                 |aura.*
| date.statement                |builtin.*
| date.transaction              |cdc.*
| date.truncate                 |coll.*
| datetime                      |date.*
| datetime.fromepoch            |datetime.*
| datetime.fromepochmillis      |db.*
| datetime.realtime             |dbms.*
| datetime.statement            |duration.*
| datetime.transaction          |graph.*
| datetime.truncate             |internal.*
| db.nameFromElementId          |localdatetime.*
| duration                      |localtime.*
| duration.between              |math.*
| duration.inDays               |plugin.*
| duration.inMonths             |point.*
| duration.inSeconds            |stored.*
| graph.byElementId             |string.*
| graph.byName                  |time.*
| graph.names                   |tx.*
| graph.propertiesByName        |unsupported.*
| localdatetime                 |vector.*
| localdatetime.realtime        |
| localdatetime.statement       |
| localdatetime.transaction     |
| localdatetime.truncate        |
| localtime                     |
| localtime.realtime            |
| localtime.statement           |
| localtime.transaction         |
| localtime.truncate            |
| point.distance                |
| point.withinBBox              |
| time                          |
| time.realtime                 |
| time.statement                |
| time.transaction              |
| time.truncate                 |
| vector.similarity.cosine      |
| vector.similarity.euclidean   |
|===

