:description: Preferred means for extending Neo4j.


[[neo4j-customized-code]]
= Neo4j customized code

Neo4j allows you to extend its functionality by writing your own code using _user-defined_ procedures and functions.
These mechanisms can be invoked directly from Cypher and are the preferred way of extending Neo4j.

Examples of use cases for procedures and functions are:

* To provide access to functionality that is not available in Cypher.
* To provide access to third-party systems.
* To perform graph-global operations, such as counting connected components or finding dense nodes.
* To express a procedural operation that is difficult to express declaratively with Cypher.

To write these procedures and functions, you must use Java and compile them into JAR files. Once compiled, these JAR files are deployed to the _NEO4J_HOME/plugins_ directory on each standalone or clustered server and loaded during start-up.
For the location of the _plugins_ directory, refer to link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/file-locations[Operations Manual -> Default file locations].

label:enterprise-only[] From Neo4j 5.14 onwards, you can use the built-in procedure `CALL dbms.reloadProcedure()` to reload procedures and functions without restarting the DBMS.
Keep in mind that in a cluster deployment, you need to call this procedure on each cluster member.

[NOTE]
====
The reload process is isolated so that the operation only affects new transactions. Currently, running transactions continue to execute with a snapshot of the available procedures at their respective initialization.
====

Procedures and functions can take arguments and return results.
In addition, procedures can perform write operations on the database.

[options="header", cols="2,3,2,2,3"]
|===

| Type
| Description
| Syntax
| Read/Write
| Cardinality

| `Procedure`
| For each row, the procedure takes parameters and returns multiple results.
| `+CALL abc(...)+`
| Update allowed.
| Changes cardinality similarly to a `MATCH` clause (0, 1, or many).

| `Scalar function`
| For each row, the function takes parameters and returns a single result.
| `+abc(...)+`
| Read-only.
| Maintains cardinality, one for one.

| `Aggregating function`
| Consumes many rows and produces an aggregated result.
| `+WITH abc(...)+`
| Read-only.
| Reduces cardinality, many down to one.

|===

Neo4j also comes bundled with a number of _built-in_ procedures and functions.

The available built-in procedures vary depending on edition and mode, as described in link:{neo4j-docs-base-uri}/operations-manual/{page-version}/reference/procedures[Operations Manual -> Procedures].
Running `SHOW PROCEDURES` displays the full list of procedures available in your Neo4j DBMS, including user-defined procedures.

The built-in functions are described in link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions[Cypher Manual -> Functions].
Running `SHOW FUNCTIONS` displays the full list of all the functions available in your Neo4j DBMS, including user-defined functions.

