:description: Preferred means for extending Neo4j.


[[neo4j-customized-code]]
= Neo4j customized code

Neo4j allows you to extend its functionality by writing your own code using _user-defined_ procedures and functions.
They can be invoked directly from Cypher and are the preferred way of extending Neo4j.

Examples of use cases for procedures and functions are:

* To provide access to functionality that is not available in Cypher.
* To provide access to third party systems.
* To perform graph-global operations, such as counting connected components or finding dense nodes.
* To express a procedural operation that is difficult to express declaratively with Cypher.

== Writing user-defined procedures and functions

Procedures and functions should be implemented in a language within the JVM ecosystem and packaged into a JAR file.
See xref:extending-neo4j/user-defined-procedures-functions.adoc#create-user-defined-procedure-or-function[Create a procedure or function] for details.

== Deploying user-defined procedures and functions

Once compiled, these JAR files are deployed to the _NEO4J_HOME/plugins_ directory on each standalone or clustered server.
For the location of the _plugins_ directory, refer to link:{neo4j-docs-base-uri}/operations-manual/{page-version}/configuration/file-locations[Operations Manual -> Default file locations].


[[comparison-of-procedures-and-functions]]
== Comparison of procedures and functions

Procedures and functions can take arguments and return results.
In addition, procedures can perform write operations on the database.

[options="header", cols="2,3,2,2,3"]
|===

| Type
| Description
| Syntax
| Read/Write
| Cardinality

| `Procedure`
| For each row the procedure takes parameters and returns multiple results.
| `+CALL abc(...)+`
| Update allowed.
| Changes cardinality similarly to a `MATCH` clause (0, 1, or many).

| `Scalar function`
| For each row the function takes parameters and returns a single result.
| `+abc(...)+`
| Read-only.
| Maintains cardinality, one for one.

| `Aggregating function`
| Consumes many rows and produces an aggregated result.
| `+WITH abc(...)+`
| Read-only.
| Reduces cardinality, many down to one.

|===

== Built-in procedures and functions

Neo4j also comes bundled with a number of _built-in_ procedures and functions.

The available built-in procedures varies depending edition and mode, as described in link:{neo4j-docs-base-uri}/operations-manual/{neo4j-version}/reference/procedures/[Operations Manual -> Procedures].
Running `SHOW PROCEDURES` will display the full list of procedures available in a particular database instance, including user-defined procedures.

The built-in functions are described in link:{neo4j-docs-base-uri}/cypher-manual/{neo4j-version}/functions/[Cypher Manual -> Functions].
Running `SHOW FUNCTIONS` will display the full list of all the functions available in a particular database instance, including user-defined functions.

