:description: Extending Neo4j with customized-built authentication and authorization plugins.


[role=enterprise-edition]
[[extending-neo4j-security-plugins]]
= Authentication and authorization plugins

This describes Neo4j support for customized-built authentication and authorization plugins.

Neo4j provides authentication and authorization plugin interfaces to support real-world deployment scenarios
not covered by native users or the built-in configuration-based LDAP connector.

The SPI (Service Provider Interface) lives in the `com.neo4j.server.security.enterprise.auth.plugin.spi` package.

Customized-built plugins have access to the xref:4.2@operations-manual:ROOT:configuration/file-locations/index.adoc[_<neo4j-home>_] directory in case you want to load any customized settings from a file located there.
Plugins can also write to the security event log.


[[extending-neo4j-authentication-plugin]]
== Authentication plugin

The authentication plugin implements the `AuthenticationPlugin` interface with the `authenticate` method.

The example below shows a minimal authentication plugin that checks for Neo4j user with Neo4j password:

[source, java]
----
@Override
public AuthenticationInfo authenticate( AuthToken authToken )
{
    String principal = authToken.principal();
    char[] credentials = authToken.credentials();

    if ( principal.equals( "neo4j" ) && Arrays.equals( credentials, "neo4j".toCharArray() ) )
    {
        return (AuthenticationInfo) () -> "neo4j";
    }
    return null;
}
----


[[extending-neo4j-authorization-plugin]]
== Authorization plugin

The authorization plugin implements the `AuthorizationPlugin` interface with the `authorize` method.

The example below shows a minimal authorization plugin that assigns the reader role to a user named neo4j:

[source, java]
----
@Override
public AuthorizationInfo authorize( Collection<PrincipalAndProvider> principals )
{
    if ( principals.stream().anyMatch( p -> "neo4j".equals( p.principal() ) ) )
    {
        return (AuthorizationInfo) () -> Collections.singleton( PredefinedRoles.READER );
    }
    return null;
}
----

Note the usage of the helper class `PredefinedRole`.


[[extending-neo4j-simplified-combined-plugin]]
== Simplified combined plugin

There is also a simplified combined plugin interface `AuthPlugin` that provides both authentication and authorization in a single method called `authenticateAndAuthorize`.

The example below shows a combined plugin verifying neo4j/neo4j credentials and returning reader role authorization:

[source, java]
----
@Override
public AuthInfo authenticateAndAuthorize( AuthToken authToken )
{
    String principal = authToken.principal();
    char[] credentials = authToken.credentials();

    if ( principal.equals( "neo4j" ) && Arrays.equals( credentials, "neo4j".toCharArray() ) )
    {
        return AuthInfo.of( "neo4j", Collections.singleton( PredefinedRoles.READER ) );
    }
    return null;
}
----


[[extending-neo4j-extendable-platform]]
== Extendable platform

Neo4j provides an extendable platform as some user deployment scenarios may not be easily configured through standard LDAP connector.
One known complexity is integrating with LDAP user directory where groups have users as a member and the not other way around.

The example below first searches for a group that the user is member of, and then maps that group to the Neo4j role by calling the customized-built `getNeo4jRoleForGroupId` method:

[source, java]
----
@Override
public AuthInfo authenticateAndAuthorize( AuthToken authToken ) throws AuthenticationException
{
    try
    {
        String username = authToken.principal();
        char[] password = authToken.credentials();

        LdapContext ctx = authenticate( username, password );
        Set<String> roles = authorize( ctx, username );

        return AuthInfo.of( username, roles );
    }
    catch ( NamingException e )
    {
        throw new AuthenticationException( e.getMessage() );
    }
}

private LdapContext authenticate( String username, char[] password ) throws NamingException
{
    Hashtable<String,Object> env = new Hashtable<>();
    env.put( Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory" );
    env.put( Context.PROVIDER_URL, "ldap://0.0.0.0:10389" );

    env.put( Context.SECURITY_PRINCIPAL, String.format( "cn=%s,ou=users,dc=example,dc=com", username ) );
    env.put( Context.SECURITY_CREDENTIALS, password );

    return new InitialLdapContext( env, null );
}

private Set<String> authorize( LdapContext ctx, String username ) throws NamingException
{
    Set<String> roleNames = new LinkedHashSet<>();

    // Set up our search controls
    SearchControls searchCtls = new SearchControls();
    searchCtls.setSearchScope( SearchControls.SUBTREE_SCOPE );
    searchCtls.setReturningAttributes( new String[]{GROUP_ID} );

    // Use a search argument to prevent potential code injection
    Object[] searchArguments = new Object[]{username};

    // Search for groups that has the user as a member
    NamingEnumeration result = ctx.search( GROUP_SEARCH_BASE, GROUP_SEARCH_FILTER, searchArguments, searchCtls );

    if ( result.hasMoreElements() )
    {
        SearchResult searchResult = (SearchResult) result.next();

        Attributes attributes = searchResult.getAttributes();
        if ( attributes != null )
        {
            NamingEnumeration attributeEnumeration = attributes.getAll();
            while ( attributeEnumeration.hasMore() )
            {
                Attribute attribute = (Attribute) attributeEnumeration.next();
                String attributeId = attribute.getID();
                if ( attributeId.equalsIgnoreCase( GROUP_ID ) )
                {
                    // Found a group that the user is a member of. See if it has a role mapped to it
                    String groupId = (String) attribute.get();
                    String neo4jGroup = getNeo4jRoleForGroupId( groupId );
                    if ( neo4jGroup != null )
                    {
                        // Yay! Add it to your set of roles
                        roleNames.add( neo4jGroup );
                    }
                }
            }
        }
    }
    return roleNames;
}
----

[TIP]
====
Read more about this and other plugin examples at link:https://github.com/neo4j/neo4j-example-auth-plugins[].
====

