:description: How to use values and types for user-defined procedures and functions.

:org-neo4j-procedure-Procedure: {neo4j-javadocs-base-uri}/org/neo4j/procedure/Procedure.html


[[extending-neo4j-procedures-and-functions-values-and-types]]
= Values and types

This describes how to work with values and types when writing user-defined procedures and functions.

The _input_ and _output_ to and from a procedure or a function must be one of the supported types, as described in xref:3.5@cypher-manual:ROOT:syntax/values/index.adoc[Cypher Manual -> Values and types].

Composite types are supported via:

* `List<T>`, where `T` is one the supported types, and
* `Map<String, Object>`, where the values in the map must have one of the supported types.

The use of `Object` is supported for the case where the type is not known beforehand.
Note, however, that the actual value must still have one of the aforementioned types.

The Cypher types and their equivalents in Java are outlined in the table below:

[[writing-procedure-types]]
.Supported types
[options="header", cols="m,m"]
|===
| Cypher type   | Java type
| String        | String
| Integer       | Long
| Float         | Double
| Boolean       | Boolean
| Point         | org.neo4j.graphdb.spatial.Point
| Date          | java.time.LocalDate
| Time          | java.time.OffsetTime
| LocalTime     | java.time.LocalTime
| DateTime      | java.time.ZonedDateTime
| LocalDateTime | java.time.LocalDateTime
| Duration      | java.time.temporal.TemporalAmount
| Node          | org.neo4j.graphdb.Node
| Relationship  | org.neo4j.graphdb.Relationship
| Path          | org.neo4j.graphdb.Path
|===

For more details, see the link:{org-neo4j-procedure-Procedure}[Neo4j Javadocs `org.neo4j.procedure.Procedure`^].

Take note that there are two cases where more than one Java type is mapped to a single Cypher type.
When this happens, type information is lost.
If the following objects are returned from procedures, the original types cannot be recreated:

* A Cypher `Duration` is created when either a `java.time.Duration` or a `java.time.Period` is provided.
  If a `Duration` is returned, only the common interface `java.time.temporal.TemporalAmount` will remain.
* A Cypher `DateTime` is created when a `java.time.OffsetDateTime` is provided.
  If a `DateTime` is returned, it will be converted into a `java.time.ZonedDateTime`.

