:description: How to open a Bolt connector to your embedded instance to get GUI administration and other benefits.

:org-neo4j-graphdb-factory-GraphDatabaseFactory: {neo4j-javadocs-base-uri}/org/neo4j/graphdb/factory/GraphDatabaseFactory.html


[[java-embedded-bolt]]
= Bolt connector

This describes how to open a Bolt connector to your embedded instance to get GUI administration and other benefits.
Accessing Neo4j embedded via the Bolt protocol.

The Neo4j Browser and the official Neo4j Drivers use the Bolt database protocol to communicate with Neo4j.
By default, Neo4j Embedded does not expose a Bolt connector, but you can enable one.
Doing so allows you to connect the services Neo4j Browser to your embedded instance.

It also gives you a way to incrementally transfer an existing Embedded application to use Neo4j Drivers instead.
Migrating to Neo4j Drivers means you can run Neo4j Embedded or Neo4j Server, without having to change your application code.

[[enable-embedded-bolt]]
To add a Bolt Connector to your embedded database, you must add the Bolt extension to your class path.
This is done by adding an additional dependency to your project:

["source", "xml", "unnumbered", "2", subs="attributes+"]
----
<project>
...
 <dependencies>

  <dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-bolt</artifactId>
    <version>{neo4j-version-exact}</version>
  </dependency>
  ...
 </dependencies>
...
</project>
----

With this dependency in place, you can configure Neo4j to enable a Bolt connector:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithBolt.java
//EmbeddedNeo4jWithBolt.java[tags=startDb]

[TIP]
====
The source code for the example can be found here:
https://github.com/neo4j/neo4j-documentation/blob/{neo4j-version}/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithBolt.java[EmbeddedNeo4jWithBolt.java^]
====

[source, java]
----
GraphDatabaseSettings.BoltConnector bolt = GraphDatabaseSettings.boltConnector( "0" );

GraphDatabaseService graphDb = new GraphDatabaseFactory()
        .newEmbeddedDatabaseBuilder( DB_PATH )
        .setConfig( bolt.type, "BOLT" )
        .setConfig( bolt.enabled, "true" )
        .setConfig( bolt.address, "localhost:7687" )
        .newGraphDatabase();
----

