:description: How to use the Cypher query language with Java.


[[cypher-java]]
= Cypher queries

In Java, you can use the xref:3.5@cypher-manual:ROOT:index.adoc[Cypher query language] as per the example below.

[TIP]
====
The source code for the examples can be found here:
link:https://github.com/neo4j/neo4j-documentation/blob/{neo4j-version}/cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java[JavaQuery.java^]
====

First, you can add some data:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
//JavaQuery.java[tags=addData]

[source, java]
----
GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase( databaseDirectory );

try ( Transaction tx = db.beginTx())
{
    Node myNode = db.createNode();
    myNode.setProperty( "name", "my node" );
    tx.success();
}
----

Execute a query:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
//JavaQuery.java[tags=execute]

[source, java]
----
try ( Transaction ignored = db.beginTx();
      Result result = db.execute( "MATCH (n {name: 'my node'}) RETURN n, n.name" ) )
{
    while ( result.hasNext() )
    {
        Map<String,Object> row = result.next();
        for ( Entry<String,Object> column : row.entrySet() )
        {
            rows += column.getKey() + ": " + column.getValue() + "; ";
        }
        rows += "\n";
    }
}
----

In the above example, you can also see how to iterate over the rows of the link:{neo4j-javadocs-base-uri}/org/neo4j/graphdb/Result.html[`org.neo4j.graphdb.Result`^].

The code will generate:

[source, output, role="noheader"]
----
n: Node[0]; n.name: my node;
----

[CAUTION]
====
When using an `Result`, you should consume the entire result (iterate over all rows using `next()`, iterating over the iterator from `columnAs()` or calling for example `resultAsString()`).
Failing to do so will not properly clean up resources used by the `Result` object, leading to unwanted behavior, such as leaking transactions.
In case you do not want to iterate over all of the results, make sure to invoke `close()` as soon as you are done, to release the resources tied to the result.
====

The recommended way to handle results is to use a link:http://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[try-with-resources statement^].
This will make sure that the result is closed at the end of the statement.

You can also get a list of the columns in the result like this:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
//JavaQuery.java[tags=columns]

[source, java]
----
List<String> columns = result.columns();
----

This gives you:

[source, output, role="noheader"]
----
[n, n.name]
----

Use the following to fetch the result items from a single column.
In this case, you will have to read the property from the node, and not from the result:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/cypher/cypher-docs/src/main/java/org/neo4j/cypher/example/JavaQuery.java
//JavaQuery.java[tags=items]

[source, java]
----
Iterator<Node> n_column = result.columnAs( "n" );
for ( Node node : Iterators.asIterable( n_column ) )
{
    nodeResult = node + ": " + node.getProperty( "name" );
}
----

In this case, there is only one node in the result:

[source, output, role="noheader"]
----
Node[0]: my node
----

Only use this if the result only contains a single column, or you are only interested in a single column of the result.

[NOTE]
====
`resultAsString()`, `writeAsStringTo()`, `columnAs()` cannot be called more than once on the same `Result` object, as they consume the result.
In the same way, part of the result gets consumed for every call to `next()`.
You should instead use only one and if you need the facilities of the other methods on the same query result instead create a new `Result`.
====

For more information on the Java interface to Cypher, see the link:{neo4j-javadocs-base-uri}/index.html[Neo4j Javadocs^].

For more information and examples for Cypher, see xref:3.5@cypher-manual:ROOT:index.adoc[Neo4j Cypher Manual].

