:description: Explicit indexes example (Deprecated).

[[java-embedded-explicit-indexes]]
[role=deprecated]
= Explicit indexes

[WARNING]
====
Explicit indexes are deprecated and due to be removed in Neo4j 4.0.
Please see link:https://neo4j.com/docs/cypher-manual/{neo4j-version}/schema/index/#schema-index-fulltext-search[Cypher Manual -> Indexes to support full-text search] to learn about using full-text schema indexes instead.
====

This demonstrates how to work with indexes with an example of a user database.

[TIP]
====
The source code used in this example is found here:
link:https://github.com/neo4j/neo4j-documentation/blob/{neo4j-version}/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithIndexing.java[EmbeddedNeo4jWithIndexing.java^]
====

First create two helper methods:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithIndexing.java
//EmbeddedNeo4jWithIndexing.java[tag=helperMethods]

[source, java]
----
private static String idToUserName( final int id )
{
    return "user" + id + "@neo4j.org";
}

private static Node createAndIndexUser( final String username )
{
    Node node = graphDb.createNode();
    node.setProperty( USERNAME_KEY, username );
    nodeIndex.add( node, USERNAME_KEY, username );
    return node;
}
----

The next step is to start the database server:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jIndexing.java
//EmbeddedNeo4jIndexing.java[tag=startDb]

[source, java]
----
graphDb = new GraphDatabaseFactory().newEmbeddedDatabase( databaseDirectory );
registerShutdownHook();
----

Now you can add some users:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jIndexing.java
//EmbeddedNeo4jIndexing.java[tag=addUsers]

[source, java]
----
try ( Transaction tx = graphDb.beginTx() )
{
    nodeIndex = graphDb.index().forNodes( "nodes" );
    // Create some users and index their names with the IndexService
    for ( int id = 0; id < 100; id++ )
    {
        createAndIndexUser( idToUserName( id ) );
    }
----

And here is how to find a user by ID:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jIndexing.java
//EmbeddedNeo4jIndexing.java[tag=findUser]

[source, java]
----
int idToFind = 45;
String userName = idToUserName( idToFind );
Node foundUser = nodeIndex.get( USERNAME_KEY, userName ).getSingle();

System.out.println( "The username of user " + idToFind + " is "
    + foundUser.getProperty( USERNAME_KEY ) );
----

[NOTE]
====
Please read xref:java-embedded/managing-resources.adoc[] on how to properly close `ResourceIterators` returned from index lookups.
====

