:description: How to create and access nodes and relationships.

:org-neo4j-graphdb-Transaction: {neo4j-javadocs-base-uri}/org/neo4j/graphdb/Transaction.html


[[java-embedded-hello-world]]
= Hello world

This describes how to create and access nodes and relationships.

For information on project setup, see xref:java-embedded/setup.adoc[].

A Neo4j graph consists of:

* nodes
* relationships that connects the nodes
* properties on both nodes and relationships

All relationships have a type.
For example, if the graph represents a social network, a relationship type could be `KNOWS`.
If a relationship of the type `KNOWS` connects two nodes, that is likely to represent two people that know each other.
A lot of the semantics of a graph is encoded in the relationship types of the application.
Although relationships are directed, they are equally traversed regardless of direction.

[TIP]
====
The source code of this example is found here:
link:https://github.com/neo4j/neo4j-documentation/blob/{neo4j-version}/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java[EmbeddedNeo4j.java]
====


== Preparing the database

Relationship types can be created by using an `enum`.
In this example, you only need a single relationship type.
This is how to define it:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=createReltype]

[source, java]
----
private enum RelTypes implements RelationshipType
{
    KNOWS
}
----

You can also prepare some variables to use:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=vars]

[source, java]
----
GraphDatabaseService graphDb;
Node firstNode;
Node secondNode;
Relationship relationship;
private DatabaseManagementService managementService;
----

The next step is to start the database server.
Note that if the directory given for the database does not already exist, it will be created.

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=startDb]

[source, java]
----
managementService = new DatabaseManagementServiceBuilder( databaseDirectory ).build();
graphDb = managementService.database( DEFAULT_DATABASE_NAME );
registerShutdownHook( managementService );
----

[NOTE]
====
Starting a database server is an expensive operation, so do not start up a new instance every time you need to interact with the database.
The instance can be shared by multiple threads, and transactions are thread confined.
====

As seen, you can register a shutdown hook that will make sure the database shuts down when the JVM exits.

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=shutdownHook]

[source, java]
----
private static void registerShutdownHook( final DatabaseManagementService managementService )
{
    // Registers a shutdown hook for the Neo4j instance so that it
    // shuts down nicely when the VM exits (even if you "Ctrl-C" the
    // running application).
    Runtime.getRuntime().addShutdownHook( new Thread()
    {
        @Override
        public void run()
        {
            managementService.shutdown();
        }
    } );
}
----

Next step is to interact with the database.


== Wrapping operations in a transaction

All operations have to be performed in a transaction.
This is a deliberate design decision, since we believe transaction demarcation to be an important part of working with a real enterprise database.
The example below illustrates transaction handling in Neo4j:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=transaction]

[source, java]
----
try ( Transaction tx = graphDb.beginTx() )
{
    // Database operations go here
    tx.commit();
}
----

For more information on transactions, see xref:transaction-management.adoc[] and the link:{org-neo4j-graphdb-Transaction}[Neo4j Javadocs for `org.neo4j.graphdb.Transaction`^].

[NOTE]
====
For brevity, wrapping of operations in a transaction is not spelled out throughout the manual.
====

== Creating a small graph

You can now create a few nodes.
The API is very intuitive as you can see in the link:{neo4j-javadocs-base-uri}/[Neo4j Javadocs] (they are included in the distribution as well). +
This is how to create a small graph consisting of two nodes, connected with one relationship and some properties:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=addData]

[source, java]
----
firstNode = tx.createNode();
firstNode.setProperty( "message", "Hello, " );
secondNode = tx.createNode();
secondNode.setProperty( "message", "World!" );

relationship = firstNode.createRelationshipTo( secondNode, RelTypes.KNOWS );
relationship.setProperty( "message", "brave Neo4j " );
----

You now have a graph that looks like this:

image::hello-world-graph-java.svg[role="middle"]

== Printing the result

After you have created your graph, you can read from it and print the result.

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=readData]

[source, java]
----
System.out.print( firstNode.getProperty( "message" ) );
System.out.print( relationship.getProperty( "message" ) );
System.out.print( secondNode.getProperty( "message" ) );
----

Which will output:

[source, output, role="noheader"]
----
Hello, brave Neo4j World!
----

[TIP]
====
For more information on how to view your graph in Neo4j Browser, see https://neo4j.com/docs/browser-manual/current/deployment-modes/dedicated-web-server/[Browser Manual -> Dedicated web server].
====

== Removing the data

In this case, the data will be removed before committing:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=removingData]

[source, java]
----
// let's remove the data
firstNode = tx.getNodeById( firstNode.getId() );
secondNode = tx.getNodeById( secondNode.getId() );
firstNode.getSingleRelationship( RelTypes.KNOWS, Direction.OUTGOING ).delete();
firstNode.delete();
secondNode.delete();
----

[NOTE]
====
Deleting a node which still has relationships when the transaction commits will fail.
This is to make sure relationships always have a start node and an end node.
====

== Shutting down the database server

Finally, shut down the database server _when the application finishes:_

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java
//EmbeddedNeo4j.java[tag=shutdownServer]

[source, java]
----
managementService.shutdown();
----

