:description: Neo4j embedded logging framework.

:org-neo4j-logging-Log: {neo4j-javadocs-base-uri}/org/neo4j/logging/Log.html
:org-neo4j-logging-LogProvider: {neo4j-javadocs-base-uri}/org/neo4j/logging/LogProvider.html
:org-neo4j-graphdb-factory-GraphDatabaseFactory: {neo4j-javadocs-base-uri}/org/neo4j/graphdb/factory/GraphDatabaseFactory.html
:org-neo4j-logging-slf4j-Slf4jLogProvider: {neo4j-javadocs-base-uri}/org/neo4j/logging/slf4j/Slf4jLogProvider.html

[[java-embedded-logging]]
= Controlling logging

This describes how to control logging in Neo4j embedded using the Neo4j embedded logging framework.

Neo4j embedded provides logging via its own link:{org-neo4j-logging-Log}[`org.neo4j.logging.Log`^] layer, and does not natively use any existing Java logging framework.
All logging events produced by Neo4j have a name, a level and a message.
The name is a FQCN (fully qualified class name).

[[log-levels]]
Neo4j uses the following log levels:
[options="header", cols='20m,80']
|===

| Level Name
| Description

| ERROR
| For serious errors that are almost always fatal.

| WARN
| For events that are serious, but not fatal.

| INFO
| Informational events.

| DEBUG
| Debugging events.

|===

[[enable-embedded-logging]]
To enable logging, an implementation of link:{org-neo4j-logging-LogProvider}[`org.neo4j.logging.LogProvider`^] must be provided to the link:{org-neo4j-graphdb-factory-GraphDatabaseFactory}[`org.neo4j.graphdb.factory.GraphDatabaseFactory`^], as follows:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithCustomLogging.java
//EmbeddedNeo4jWithCustomLogging.java[tag=startDbWithLogProvider]

[source, java]
----
LogProvider logProvider = new MyCustomLogProvider( output );
graphDb = new GraphDatabaseFactory().setUserLogProvider( logProvider ).newEmbeddedDatabase( databaseDirectory );
----

Neo4j also includes a binding for SLF4J, which is available in the `neo4j-slf4j` library jar.
This can be obtained via Maven:

[source, xml]
----
<project>
...
 <dependencies>
  <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j-slf4j</artifactId>
   <version>3.5.30</version>
  </dependency>
  <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>${slf4j-version}</version>
  </dependency>
  ...
 </dependencies>
...
</project>
----

To use this binding, pass an instance of link:{org-neo4j-logging-slf4j-Slf4jLogProvider}[`org.neo4j.logging.slf4j.Slf4jLogProvider`^] to the link:{org-neo4j-graphdb-factory-GraphDatabaseFactory}[`org.neo4j.graphdb.factory.GraphDatabaseFactory`^], as follows:

//https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithSLF4JLogging.java
//EmbeddedNeo4jWithSLF4JLogging.java[tag=startDbWithSlf4jLogProvider]

[source, java]
----
graphDb = new GraphDatabaseFactory().setUserLogProvider( new Slf4jLogProvider() )
        .newEmbeddedDatabase( databaseDirectory );
----

All log output can then be controlled via SLF4J configuration.

