:description: Traversal API.


[[java-embedded-traversal]]
= Traversal

[abstract]
--
This page describes how to traverse a graph using the <<traversal, Traversal Framework>>.
--

== The Matrix example

This example of a traversed graph uses some of the characters featured in the film trilogy "The Matrix".
The source code can be found here: link:https://github.com/neo4j/neo4j-documentation/blob/{neo4j-version}/embedded-examples/src/main/java/org/neo4j/examples/NewMatrix.java[NewMatrix.java].

image::examples-matrix.svg[title="Matrix node space view"]

Here is an example of how to define the `TraversalDescription` to find all the friends, and friend of friends, of a given person and how to return the results excluding the initial person:

[source, java]
----
private Traverser getFriends( Transaction transaction, final Node person )
{
    TraversalDescription td = transaction.traversalDescription()
            .breadthFirst()
            .relationships( RelTypes.KNOWS, Direction.OUTGOING )
            .evaluator( Evaluators.excludeStartPosition() );
    return td.traverse( person );
}
----

To perform the actual traversal and print the names of all found friends, do the following:

[source, java]
----
int numberOfFriends = 0;
String output = neoNode.getProperty( "name" ) + "'s friends:\n";
Traverser friendsTraverser = getFriends( tx, neoNode );
for ( Path friendPath : friendsTraverser )
{
    output += "At depth " + friendPath.length() + " => "
              + friendPath.endNode()
                      .getProperty( "name" ) + "\n";
    numberOfFriends++;
}
output += "Number of friends found: " + numberOfFriends + "\n";
----

It should give this output:

[source, output, role="noheader"]
----
Thomas Anderson's friends:
At depth 1 => Morpheus
At depth 1 => Trinity
At depth 2 => Cypher
At depth 3 => Agent Smith
Number of friends found: 4
----

=== Who coded the Matrix?
To find the master mind behind "The Matrix", follow all outgoing relationships which have the type `KNOWS` or `CODED_BY`.
The final node connected to the relationship `CODED_BY` will be the Matrix's coder.

[source, java]
----
private Traverser findHackers( Transaction transaction, final Node startNode )
{
    TraversalDescription td = transaction.traversalDescription()
        .breadthFirst()
        .relationships( RelTypes.CODED_BY, Direction.OUTGOING )
        .relationships( RelTypes.KNOWS, Direction.OUTGOING )
        .evaluator(Evaluators.includeWhereLastRelationshipTypeIs( RelTypes.CODED_BY ) );
    return td.traverse( startNode );
}
----

Here is how to print out the result and find all hackers:

[source, java]
----
String output = "Hackers:\n";
int numberOfHackers = 0;
Traverser traverser = findHackers( tx, getNeoNode( tx ) );
for ( Path hackerPath : traverser )
{
    output += "At depth " + hackerPath.length() + " => " + hackerPath.endNode().getProperty( "name" ) + "\n";
    numberOfHackers++;
}
output += "Number of hackers found: " + numberOfHackers + "\n";
----

Now you know who coded the Matrix:

[source, output, role="noheader"]
----
Hackers:
At depth 4 => The Architect
Number of hackers found: 1
----


=== Walking an ordered path

The following example shows how to use a custom `Evaluator` to find paths that adhere to a predefined order.
The source code can be found here: link:https://github.com/neo4j/neo4j-documentation/blob/{neo4j-version}/embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java[OrderedPath.java].

To create the example graph that will be traversed over, do the following:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java
//OrderedPath.java[tag=createGraph]

[source, java]
----
Node A = tx.createNode();
Node B = tx.createNode();
Node C = tx.createNode();
Node D = tx.createNode();

A.createRelationshipTo( C, REL2 );
C.createRelationshipTo( D, REL3 );
A.createRelationshipTo( B, REL1 );
B.createRelationshipTo( C, REL2 );
----

image::example-ordered-path.svg[role="middle"]

When setting up the traversal of the graph, store the order of the relationships (`REL1` -> `REL2` -> `REL3`) in an `ArrayList`.
Upon traversal, the `Evaluator` can check against it to ensure that the only paths included and returned have the predefined order of relationships:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java
//OrderedPath.java[tag=walkOrderedPath]

[source, java]
----
final ArrayList<RelationshipType> orderedPathContext = new ArrayList<>();
orderedPathContext.add( REL1 );
orderedPathContext.add( REL2 );
orderedPathContext.add( REL3 );
TraversalDescription td = tx.traversalDescription()
    .evaluator( new Evaluator()
    {
        @Override
        public Evaluation evaluate( final Path path )
        {
            if ( path.length() == 0 )
            {
                return Evaluation.EXCLUDE_AND_CONTINUE;
            }
            RelationshipType expectedType = orderedPathContext.get( path.length() - 1 );
            boolean isExpectedType = path.lastRelationship()
                    .isType( expectedType );
            boolean included = path.length() == orderedPathContext.size() && isExpectedType;
            boolean continued = path.length() < orderedPathContext.size() && isExpectedType;
            return Evaluation.of( included, continued );
        }
    } )
    .uniqueness( Uniqueness.NODE_PATH ); //<1>
----

Note that the uniqueness was set to `Uniqueness.NODE_PATH`.
This makes it possible to revisit the same node during the traversal, but not the same path.

To perform the traversal and print all ordered paths found, do the following:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java
//OrderedPath.java[tag=printPath]

[source, java]
----
Traverser traverser = td.traverse( tx.getNodeById( A.getId() ) );
PathPrinter pathPrinter = new PathPrinter( "name" );
for ( Path path : traverser )
{
    output += Paths.pathToString( path, pathPrinter );
}
----

This should be the output:

[source, output, role="noheader"]
----
(A)--[REL1]-->(B)--[REL2]-->(C)--[REL3]-->(D)
----

In this case, a customized class is used to format the path output.
See how to do it:

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/main/java/org/neo4j/examples/orderedpath/OrderedPath.java
//OrderedPath.java[tag=pathPrinter]

[source, java]
----
static class PathPrinter implements Paths.PathDescriptor<Path>
{
    private final String nodePropertyKey;

    public PathPrinter( String nodePropertyKey )
    {
        this.nodePropertyKey = nodePropertyKey;
    }

    @Override
    public String nodeRepresentation( Path path, Node node )
    {
        return "(" + node.getProperty( nodePropertyKey, "" ) + ")";
    }

    @Override
    public String relationshipRepresentation( Path path, Node from, Relationship relationship )
    {
        String prefix = "--", suffix = "--";
        if ( from.equals( relationship.getEndNode() ) )
        {
            prefix = "<--";
        }
        else
        {
            suffix = "-->";
        }
        return prefix + "[" + relationship.getType().name() + "]" + suffix;
    }
}
----


[[examples-uniqueness-of-paths-in-traversals]]
== Uniqueness of Paths in traversals

The follow example demonstrates the use of node uniqueness.
It lists all pets descended from other pets that are owned by `Principal1`:

.Descendants example graph
image:uniqueness-of-paths-in-traversals-graph.svg[role="middle"]

In order to return all descendants of `Pet0` which are owned by `Principal1` (i.e. `Pet1` and `Pet3`), the uniqueness of the traversal needs to be set to `NODE_PATH` rather than the default `NODE_GLOBAL`.
This way nodes can be traversed more than once, and paths that have different nodes with some in common (like the start and the end nodes) can be returned.

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/test/java/org/neo4j/examples/UniquenessOfPathsDocTest.java
//UniquenessOfPathsDocTest.java[tag=traverser]

[source, java]
----
Node dataTarget = data.get().get( "Principal1" );
String output = "";
int count = 0;
try ( Transaction transaction = graphdb().beginTx() )
{
    start = transaction.getNodeById( start.getId() );
    final Node target = transaction.getNodeById( dataTarget.getId() );
    TraversalDescription td = transaction.traversalDescription()
            .uniqueness( Uniqueness.NODE_PATH )
            .evaluator( new Evaluator()
    {
        @Override
        public Evaluation evaluate( Path path )
        {
            boolean endNodeIsTarget = path.endNode().equals( target );
            return Evaluation.of( endNodeIsTarget, !endNodeIsTarget );
        }
    } );

    Traverser results = td.traverse( start );
}
----

This will return the following paths:

[source, output, role="noheader"]
----
(2)-[descendant,2]->(0)<-[owns,5]-(1)
(2)-[descendant,0]->(5)<-[owns,3]-(1)
----

To see how this differs from using `NODE_GLOBAL` uniqueness, do the following.
Note that the `TraversalDescription` object is immutable, so a new instance is required.

//https://github.com/neo4j/neo4j-documentation/blob/dev/embedded-examples/src/test/java/org/neo4j/examples/UniquenessOfPathsDocTest.java
//UniquenessOfPathsDocTest.java[tag=traverseNodeGlobal]

[source, java]
----
TraversalDescription nodeGlobalTd = tx.traversalDescription().uniqueness( Uniqueness.NODE_PATH ).evaluator( new Evaluator()
{
    @Override
    public Evaluation evaluate( Path path )
    {
        boolean endNodeIsTarget = path.endNode().equals( target );
        return Evaluation.of( endNodeIsTarget, !endNodeIsTarget );
    }
} ).uniqueness( Uniqueness.NODE_GLOBAL );
Traverser results = nodeGlobalTd.traverse( start );
----

Now only one path is returned because the node `Principal1` can only be traversed once:

[source, output, role="noheader"]
----
(2)-[descendant,2]->(0)<-[owns,5]-(1)
----
